services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      APP_NAME: Prueba_Tecnica
      MONGO_URI: mongodb+srv://rsannarain:rsannarain@cluster0.hikbp2g.mongodb.net/
    command: npm run dev
